# Generated by Django 3.2.3 on 2021-09-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_userdetail_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='pic',
            field=models.ImageField(default='static/thumbnail/default_avatar.png', upload_to='profiles'),
        ),
    ]
