# Generated by Django 3.2.3 on 2021-09-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_userdetail_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='pic',
            field=models.ImageField(default='', upload_to='profiles'),
        ),
    ]
