# Generated by Django 3.2.3 on 2021-09-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userdetail_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=112, unique=True)),
                ('title', models.CharField(max_length=112)),
                ('des', models.TextField()),
                ('public', models.CharField(default='public', max_length=50)),
                ('pic', models.ImageField(default='', upload_to='thumbnail')),
                ('blog', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=112, unique=True)),
                ('blogurl', models.CharField(max_length=112)),
            ],
        ),
    ]
