# Generated by Django 3.2.3 on 2021-09-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_blogs_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='pic',
            new_name='thumb',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='username',
            field=models.CharField(max_length=112),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='username',
            field=models.CharField(max_length=112),
        ),
    ]
