# Generated by Django 3.2.3 on 2021-09-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210904_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='username',
            new_name='user',
        ),
    ]
