# Generated by Django 3.2.3 on 2021-09-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_username_blogs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='name',
            field=models.CharField(default='none', max_length=112),
            preserve_default=False,
        ),
    ]
