# Generated by Django 3.2.3 on 2021-09-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_blogs_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='user',
        ),
        migrations.AddField(
            model_name='blogs',
            name='owner',
            field=models.CharField(default='none', max_length=112),
            preserve_default=False,
        ),
    ]
