# Generated by Django 3.2.3 on 2021-09-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210904_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogs',
        ),
    ]
