# Generated by Django 3.2.3 on 2021-09-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_blogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=112)),
                ('title', models.CharField(max_length=112)),
                ('des', models.TextField()),
                ('public', models.CharField(default='public', max_length=50)),
                ('thumb', models.ImageField(default='', upload_to='thumbnail')),
                ('blog', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='blogs',
        ),
    ]
