# Generated by Django 3.2.3 on 2021-09-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210904_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='blogurl',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='blogid',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
